# Generated by Django 4.1.2 on 2022-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Friend", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "word",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
